### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'get'

### ISSUE THREAD

**Issue by nf78** [iamDecode/sklearn-pmml-model#11]
When loading a PMML model with the following structure:

Regression > RegressionTable > NumericPredictor

I get the following error, when trying to import the model with:

`clf = PMMLLinearRegression(pmml="filename.pmml")`

```
Traceback (most recent call last):
  File "test.py", line 23, in <module>
    clf = PMMLLinearRegression(pmml="alexupdate3.pmml")
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python36\sklearn_pmml_model\linear_model\implementations.py", line 27, in __init__
    super().__init__(pmml)
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python36\sklearn_pmml_model\linear_model\base.py", line 32, in __init__
    for field in fields
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python36\sklearn_pmml_model\linear_model\base.py", line 33, in <listcomp>
    if field.tag == 'DataField'
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python36\sklearn_pmml_model\linear_model\base.py", line 25, in encoder_for
    encoder.categories_ = np.array([self.field_mapping[field.get('name')][1].categories])
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python36\lib\site-packages\cached_property.py", line 35, in __get__
    value = obj.__dict__[self.func.__name__] = self.func(obj)
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python36\sklearn_pmml_model\base.py", line 61, in field_mapping
    for name, e in fields.items()
  File "C:\Users\<user>\AppData\Local\Programs\Python\Python36\sklearn_pmml_model\base.py", line 62, in <dictcomp>
    if e.tag == 'DerivedField'
AttributeError: 'NoneType' object has no attribute 'get'
```

**Comment by nf78** [comment]
Here is a snippet inside the PMML file, in case you need it

`<DerivedField name="lowercase(error_comb)" optype="categorical" dataType="string">
			<Apply function="lowercase">
				<FieldRef field="error_comb"/>
			</Apply>
		</DerivedField>
		<DerivedField name="tf($25,000)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">$25,000</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf($50)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">$50</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf($50 and)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">$50 and</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf($500)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">$500</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf($500 lower)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">$500 lower</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf(+44(0)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">+44(0</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf(+44(0 20)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">+44(0 20</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf(0)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">0</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf(0 col)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">0 col</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf(0 getinsurancescoregroup)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">0 getinsurancescoregroup</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf(0 years)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">0 years</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf(0.03)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">0.03</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf(0014)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">0014</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf(0014 and)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">0014 and</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf(0014 where)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">0014 where</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf(003)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">003</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf(003 calls)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">003 calls</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf(0040)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">0040</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf(0040 calls)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">0040 calls</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf(01)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">01</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf(01 or)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">01 or</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf(01/1900)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">01/1900</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf(0116)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">0116</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf(0116 281)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">0116 281</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf(013)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">013</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf(013 88)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">013 88</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf(01502)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">01502</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf(01502 727)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">01502 727</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf(01733)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">01733</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf(01733 224)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">01733 224</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf(02)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">02</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf(02 from)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">02 from</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf(03)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">03</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf(03 numbers)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">03 numbers</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf(0324)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">0324</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf(0324 324)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">0324 324</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf(0330)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">0330</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf(0330 100)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">0330 100</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf(0330 102)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">0330 102</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf(0330 303)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">0330 303</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf(0333)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">0333</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf(0333 043)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">0333 043</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf(0333 2202)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">0333 2202</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf(0333 234)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">0333 234</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf(0344)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">0344</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf(0344 412)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">0344 412</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf(0344 481)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">0344 481</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf(0344 numbers)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">0344 numbers</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf(0345)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">0345</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf(0345 172)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">0345 172</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf(0345 246)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">0345 246</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf(043)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">043</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf(043 2066)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">043 2066</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf(0652)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">0652</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf(0652 or)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">0652 or</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf(072)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">072</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf(072 1146)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">072 1146</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf(0800)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">0800</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf(0800 013)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">0800 013</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf(0800 0324)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">0800 0324</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf(0800 072)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">0800 072</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf(0800 092)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">0800 092</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf(0800 597)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">0800 597</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf(0800 916)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">0800 916</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf(0800 988)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">0800 988</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf(0800 numbers)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">0800 numbers</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf(0800 or)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">0800 or</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf(0844)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">0844</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf(0844 842)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">0844 842</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf(08442)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">08442</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf(08442 411)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">08442 411</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf(08459003649)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">08459003649</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf(092)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">092</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf(092 1284)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">092 1284</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf(1)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">1</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf(1 1)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">1 1</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf(1 and)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">1 and</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf(1 click)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">1 click</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf(1 county)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">1 county</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf(1 driver)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">1 driver</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf(1 letter)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">1 letter</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf(1 of)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">1 of</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf(1 products)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">1 products</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf(1 surcharge)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">1 surcharge</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf(1 ticket)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">1 ticket</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf(1 traveler)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">1 traveler</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf(1 tries)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">1 tries</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf(1 years)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">1 years</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf(1-10)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">1-10</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf(1-30)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">1-30</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf(1-30 characters)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">1-30 characters</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf(1-800-257-7544)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">1-800-257-7544</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf(1-800-257-7544 to)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">1-800-257-7544 to</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf(1-855-cspire5)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">1-855-cspire5</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf(1-855-cspire5 277-4735)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">1-855-cspire5 277-4735</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf(1-855-get100x)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">1-855-get100x</Constant>
			</Apply>
		</DerivedField>
		<DerivedField name="tf(1-855-get100x 438-1009)" optype="continuous" dataType="integer">
			<Apply function="tf">
				<FieldRef field="lowercase(error_comb)"/>
				<Constant dataType="string">1-855-get100x 438-1009</Constant>
			</Apply>
		</DerivedField>`

**Comment by iamDecode** [comment]
Thanks for the feedback. Data pipeline operations like applying functions on fields are not yet supported. `DerivedField` is currently assumed to have a `FieldRef`, which is not mandatory. This s where the code fails. Properly supporting alternative expressions for `DerivedField` should be investigated.

Reference: http://dmg.org/pmml/v4-3/Transformations.html#xsdGroup_EXPRESSION
