### ISSUE TITLE
Error while importing the model

### ISSUE THREAD

**Issue by lakshman-1396** [iamDecode/sklearn-pmml-model#18]
from sklearn_pmml_model.ensemble import PMMLForestClassifier 

Error: numpy.ufunc size changed, may indicate binary incompatibility. Expected 216from C header, got 192 from PyObject

**Comment by iamDecode** [comment]
This is an issue with NumPy. You have got a few options to fix this:
- Recompiling the library yourself. In doing so the library is compiled with the same numpy version as you use in your project.
- Use a different version of numpy, some reports [here](https://github.com/scikit-image/scikit-image/issues/3655#issuecomment-484382609) suggest version 1.16.1 should work, but you would have to experiment yourself.

**Comment by lakshman-1396** [comment]
I tried to install it manually using python setup.py install
i am getting the following error
>>> import sklearn_pmml_model
>>> from sklearn_pmml_model import tree
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "\\ns-sisci01hd\home_s01\Citrix_Folder_Redirect\My Documents\sklearn-pmml-model\sklearn_pmml_model\tree\__init__.
py", line 6, in <module>
    from .tree import PMMLTreeClassifier, construct_tree
  File "\\ns-sisci01hd\home_s01\Citrix_Folder_Redirect\My Documents\sklearn-pmml-model\sklearn_pmml_model\tree\tree.py",
 line 4, in <module>
    from sklearn_pmml_model.tree._tree import Tree, NODE_DTYPE, TREE_LEAF, TREE_UNDEFINED
ModuleNotFoundError: No module named 'sklearn_pmml_model.tree._tree'

**Comment by iamDecode** [comment]
Hmm thats curious, setup should compile the Cython modules. To ensure the install works, run `python setup.py build_ext --inplace` first, then run `python setup.py install`.

**Comment by lakshman-1396** [comment]
Same error. Cython modules are compiled during the build.

PS Microsoft.PowerShell.Core\FileSystem::\\ns-sisci01hd\home_s01\Citrix_Folder_Redirect\My Documents\sklearn-pmml-model\build\lib.win-amd64-3.6\sklearn_pmml_model> cd "\\ns-sisci01
hd\home_s01\Citrix_Folder_Redirect\My Documents\sklearn-pmml-model\build\lib.win-amd64-3.6"
PS Microsoft.PowerShell.Core\FileSystem::\\ns-sisci01hd\home_s01\Citrix_Folder_Redirect\My Documents\sklearn-pmml-model\build\lib.win-amd64-3.6> python
Python 3.6.3 |Anaconda, Inc.| (default, Oct 15 2017, 03:27:45) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from sklearn_pmml_model.ensemble import PMMLForestClassifier
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "\\ns-sisci01hd\home_s01\Citrix_Folder_Redirect\My Documents\sklearn-pmml-model\build\lib.win-amd64-3.6\sklearn_pmml_model\ensemble\__init__.py", line 6, in <module>
    from .forest import PMMLForestClassifier
  File "\\ns-sisci01hd\home_s01\Citrix_Folder_Redirect\My Documents\sklearn-pmml-model\build\lib.win-amd64-3.6\sklearn_pmml_model\ensemble\forest.py", line 3, in <module>
    from sklearn_pmml_model.tree._tree import Tree, NODE_DTYPE
  File "\\ns-sisci01hd\home_s01\Citrix_Folder_Redirect\My Documents\sklearn-pmml-model\build\lib.win-amd64-3.6\sklearn_pmml_model\tree\__init__.py", line 6, in <module>
    from .tree import PMMLTreeClassifier, construct_tree
  File "\\ns-sisci01hd\home_s01\Citrix_Folder_Redirect\My Documents\sklearn-pmml-model\build\lib.win-amd64-3.6\sklearn_pmml_model\tree\tree.py", line 4, in <module>
    from sklearn_pmml_model.tree._tree import Tree, NODE_DTYPE, TREE_LEAF, TREE_UNDEFINED
ModuleNotFoundError: No module named 'sklearn_pmml_model.tree._tree'

**Comment by iamDecode** [comment]
Alright, I have recently introduced building wheels for the sole purpose of preventing issues with compiling, so let's not go there.

I have gone over all recent numpy versions up to a year ago and found that your original problem only occurs for numpy versions lower than 1.16.0. I have added a constraint to the installation such that this problem is automatically fixed upon pip install. (There were some more compatibility issues with the most recent version of scikit-learn that have been fixed too.)

Could you try using the library again by installing it with `pip install sklearn_pmml_model==0.0.13`? As far as I was able to test, this versions works.

**Comment by iamDecode** [comment]
Closing this issue due to inactivity. I expect the problem to be fixed, if not please let me know!
