### ISSUE TITLE
Error on installation

### ISSUE THREAD

**Issue by Harpsichord1207** [iamDecode/sklearn-pmml-model#4]
Got an error when installing with pip:
```
$ pip install sklearn-pmml-model
Collecting sklearn-pmml-model
  Downloading https://files.pythonhosted.org/packages/c7/93/3e6f09020fe4be2b61dd49367d93cbf826c7544057411c5c2704fc53315f/sklearn-pmml-model-0.0.2.tar.gz (489kB)
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\liutao3\AppData\Local\Temp\pip-install-q74z6z6i\sklearn-pmml-model\setup.py", line 45, in <module>
        Extension("sklearn_pmml_model.tree._utils", ["sklearn_pmml_model/tree/_utils.pyx"], include_dirs=[np.get_include()]),
      File "e:\machinelearning\venv\lib\site-packages\Cython\Build\Dependencies.py", line 967, in cythonize
        aliases=aliases)
      File "e:\machinelearning\venv\lib\site-packages\Cython\Build\Dependencies.py", line 812, in create_extension_list
        for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
      File "e:\machinelearning\venv\lib\site-packages\Cython\Build\Dependencies.py", line 111, in nonempty
        raise ValueError(error_msg)
    ValueError: 'sklearn_pmml_model/tree/_tree.pyx' doesn't match any files

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\liutao3\AppData\Local\Temp\pip-install-q74z6z6i\sklearn-pmml-model\
You are using pip version 18.1, however version 19.0.1 is available.
You should consider upgrading via the 'python -m pip install --upgrade pip' command.
```

**Comment by Harpsichord1207** [comment]
Thanks for fixing the  installation problem, I successfully installed sklearn_pmml_model. But I got another exception, my code is 
```
from sklearn_pmml_model.tree import PMMLTreeClassifier

clf = PMMLTreeClassifier(pmml="model.pmml")
```

And the error:
```
Traceback (most recent call last):
  File "/home/liutao3/GeekWeek/sklearn_pmml_model_test.py", line 8, in <module>
    clf = PMMLTreeClassifier(pmml="model.pmml")
  File "/root/Desktop/Py3env/lib/python3.7/site-packages/sklearn_pmml_model/tree/tree.py", line 131, in __init__
    nodes, values = self.construct_tree(firstNode)
  File "/root/Desktop/Py3env/lib/python3.7/site-packages/sklearn_pmml_model/tree/tree.py", line 73, in construct_tree
    left_node, left_value = self.construct_tree(childNodes[0], i + 1)
  File "/root/Desktop/Py3env/lib/python3.7/site-packages/sklearn_pmml_model/tree/tree.py", line 73, in construct_tree
    left_node, left_value = self.construct_tree(childNodes[0], i + 1)
  File "/root/Desktop/Py3env/lib/python3.7/site-packages/sklearn_pmml_model/tree/tree.py", line 73, in construct_tree
    left_node, left_value = self.construct_tree(childNodes[0], i + 1)
  [Previous line repeated 1 more times]
  File "/root/Desktop/Py3env/lib/python3.7/site-packages/sklearn_pmml_model/tree/tree.py", line 75, in construct_tree
    right_node, right_value = self.construct_tree(childNodes[1], i + 1 + offset)
  File "/root/Desktop/Py3env/lib/python3.7/site-packages/sklearn_pmml_model/tree/tree.py", line 73, in construct_tree
    left_node, left_value = self.construct_tree(childNodes[0], i + 1)
  File "/root/Desktop/Py3env/lib/python3.7/site-packages/sklearn_pmml_model/tree/tree.py", line 73, in construct_tree
    left_node, left_value = self.construct_tree(childNodes[0], i + 1)
  File "/root/Desktop/Py3env/lib/python3.7/site-packages/sklearn_pmml_model/tree/tree.py", line 73, in construct_tree
    left_node, left_value = self.construct_tree(childNodes[0], i + 1)
  File "/root/Desktop/Py3env/lib/python3.7/site-packages/sklearn_pmml_model/tree/tree.py", line 75, in construct_tree
    right_node, right_value = self.construct_tree(childNodes[1], i + 1 + offset)
  File "/root/Desktop/Py3env/lib/python3.7/site-packages/sklearn_pmml_model/tree/tree.py", line 86, in construct_tree
    value = struct.pack('d', value) # d = double = float64
struct.error: required argument is not a float
```

**Comment by iamDecode** [comment]
Thanks for the feedback. The library is very much in alpha stage so I cannot ensure it is very robust against different PMML models yet. The error you mentioned is a valid one though, and was easily fixed in commit f54725c23120a04839139c8d4ae2c5864709383e. Let me know if you run into more issues.

**Comment by Harpsichord1207** [comment]
Hello, sorry to replay so late, after I applied the change in [f54725c](https://github.com/iamDecode/sklearn-pmml-model/commit/f54725c23120a04839139c8d4ae2c5864709383e), the error also changed to:
```
Traceback (most recent call last):
  File "/home/liutao3/GeekWeek/sklearn_pmml_model_test.py", line 7, in <module>
    clf = PMMLTreeClassifier(pmml="model.pmml")
  File "/root/Desktop/Py3env/lib/python3.7/site-packages/sklearn_pmml_model/tree/tree.py", line 131, in __init__
    nodes, values = self.construct_tree(firstNode)
  File "/root/Desktop/Py3env/lib/python3.7/site-packages/sklearn_pmml_model/tree/tree.py", line 73, in construct_tree
    left_node, left_value = self.construct_tree(childNodes[0], i + 1)
  File "/root/Desktop/Py3env/lib/python3.7/site-packages/sklearn_pmml_model/tree/tree.py", line 73, in construct_tree
    left_node, left_value = self.construct_tree(childNodes[0], i + 1)
  File "/root/Desktop/Py3env/lib/python3.7/site-packages/sklearn_pmml_model/tree/tree.py", line 73, in construct_tree
    left_node, left_value = self.construct_tree(childNodes[0], i + 1)
  [Previous line repeated 1 more times]
  File "/root/Desktop/Py3env/lib/python3.7/site-packages/sklearn_pmml_model/tree/tree.py", line 75, in construct_tree
    right_node, right_value = self.construct_tree(childNodes[1], i + 1 + offset)
  File "/root/Desktop/Py3env/lib/python3.7/site-packages/sklearn_pmml_model/tree/tree.py", line 73, in construct_tree
    left_node, left_value = self.construct_tree(childNodes[0], i + 1)
  File "/root/Desktop/Py3env/lib/python3.7/site-packages/sklearn_pmml_model/tree/tree.py", line 73, in construct_tree
    left_node, left_value = self.construct_tree(childNodes[0], i + 1)
  File "/root/Desktop/Py3env/lib/python3.7/site-packages/sklearn_pmml_model/tree/tree.py", line 73, in construct_tree
    left_node, left_value = self.construct_tree(childNodes[0], i + 1)
  File "/root/Desktop/Py3env/lib/python3.7/site-packages/sklearn_pmml_model/tree/tree.py", line 75, in construct_tree
    right_node, right_value = self.construct_tree(childNodes[1], i + 1 + offset)
  File "/root/Desktop/Py3env/lib/python3.7/site-packages/sklearn_pmml_model/tree/tree.py", line 86, in construct_tree
    value = struct.pack('d', float(value)) # d = double = float64
TypeError: float() argument must be a string or a number, not 'Interval'
```

**Comment by iamDecode** [comment]
Ah no worries, and thanks again for letting me know. `Interval` specification used to be supported, but was broken during the cython tree update. The information about the interval cannot currently be used, but it was not properly disregarded. I made some changes in 7b00588c18cbbb6172c5daab3238b492f97a1d62 to address this, so it should be fixed. 

In case something else goes wrong, would you perhaps be willing to share the pmml model and test data you are using? I should be able to address problems quicker that way.

**Comment by iamDecode** [comment]
Also, please make a new issue for any further issues. Im closing this as the initial installation error was fixed.
